{ pkgs, ... }:
let
  # Same derivation `nixos/packages/dev.nix` installs - see rust-toolchain.nix for why there is
  # exactly one. rustc here is 1.98.0; nixpkgs' standalone `rust-analyzer` is the 2026-08-03
  # release, i.e. older than the proc-macro server that ships in the toolchain's `rustc`
  # component (`$(rustc --print sysroot)/libexec/rust-analyzer-proc-macro-srv`).
  rust = import ../../../../rust-toolchain.nix { inherit pkgs; };
in
{
  # nixvim's own dependency for this plugin (`dependencies = [ "rust-analyzer" ]` in
  # plugins/by-name/rustaceanvim/default.nix -> `dependencies.rust-analyzer.enable` mkDefault
  # true) would put *nixpkgs'* rust-analyzer first on the nvim wrapper PATH. Repointing that
  # dependency at the toolchain puts `<toolchain>/bin` first instead, so rustaceanvim's default
  # cmd (`{ 'rust-analyzer', '--log-file', ... }`), the `cargo` its runnables/fly-check invoke
  # and the proc-macro server are all one release.
  # This is a top-level option, not a `plugins.rustaceanvim.*` one - `plugins.<name>.package`
  # would replace the *vim plugin*, not the server.
  # No closure cost: the toolchain is already installed via nixos/packages/dev.nix.
  # PATH precedence, measured on the built wrapper: nixvim's own rust-analyzer used to be the
  # only hit (`which -a rust-analyzer` -> ...rust-analyzer-2026-08-03/bin/rust-analyzer), and
  # dependencies land *after* conform's tools, so `rustfmt` still resolves to conform's
  # rustfmt-1.97.1 - the same binary rust-analyzer and `<leader>cf` would call, so formatting
  # stays self-consistent inside nvim (1.97.1 formatter with a 1.98.0 server is fine; rustfmt's
  # CLI is stable). `cargo`/`rustc` point at this very toolchain either way.
  dependencies.rust-analyzer.package = rust;

  # ---- Rust ----
  plugins.rustaceanvim = {
    enable = true;

    settings = {
      # `server.default_settings` is what rust-analyzer receives as its configuration; the
      # `"rust-analyzer"` key is rustaceanvim's own namespacing convention (it merges the
      # namespace away before `workspace/didChangeConfiguration`).
      server.default_settings."rust-analyzer" = {
        # Diagnostics from `cargo clippy` instead of `cargo check`. `tools.enable_clippy`
        # (plugin default true) only flips this when it *detects* clippy; setting it here
        # makes it deterministic and also covers `:RustLsp flyCheck`.
        check = {
          command = "clippy";
          allTargets = true; # tests, benches, examples - not just the lib
        };

        # Proc macros: the reason for the toolchain pin above. Explicit so a future
        # `dependencies.rust-analyzer` change is visible as a mismatch here.
        procMacro.enable = true;

        # Code generated by build.rs (tonic, cxx, bindgen, winapi ...) is otherwise invisible
        # to completion/goto. Plugin default is true as well; pinned for the same reason.
        cargo.buildScripts.enable = true;

        # `ref mut binding @ subpattern` hints - the one hint class rust-analyzer does not
        # enable by default.
        inlayHints.bindingModeHints.enable = true;

        # NOT set: `rustfmt.extraArgs`. rust-analyzer already passes `--edition <crate edition>`
        # (from the cargo model) and conform's `rustfmt` parses the edition out of Cargo.toml
        # (default_edition = "2021"), so a hardcoded `--edition 2024` would apply one crate's
        # edition to every crate. Only add flags here that are edition-independent.
      };

      # Runnables/debuggables in a native terminal split (`termopen` = plugin default, spelled
      # out because "quickfix" - the other legal value here - cannot run interactive binaries,
      # which is most of what `:RustLsp runnables` is for).
      # Legal values: termopen | quickfix | toggleterm | vimux | neotest
      # (plugins/by-name/rustaceanvim/settings-options.nix).
      tools.executor = "termopen";

      # `dap.adapter` left at its default - and that default is now *satisfied* rather
      # than hoped for (rustaceanvim 9.2.0, lua/rustaceanvim/config/internal.lua): with no
      # `codelldb` on PATH it probes `lldb-dap` before `lldb-vscode` and yields an
      # *executable* adapter named "lldb"; if that probe fails it returns `false` and
      # `:RustLsp debuggables` refuses to run even though an adapter exists. Two lines in
      # plugins/dap.nix take care of it:
      #   * `extraPackages = [ pkgs.lldb ]`  -> `lldb-dap` resolvable by name, probe succeeds;
      #   * `plugins.dap.adapters.executables.lldb` -> `dap.adapters.lldb` is non-nil, and
      #     dap.lua only assigns its own when the key is nil
      #     (`if dap.adapters[adapter_key] == nil`), so debuggables run through the
      #     store-pinned binary from dap.nix.
      # Verified with the built wrapper: lldb-dap answers `initialize`, reports `stopped`,
      # terminates cleanly - the same adapter the c/cpp configurations use.
    };
  };

  # ---- Rust-only keymaps ----
  # `:RustLsp` is a *buffer-local* user command: rustaceanvim creates it with
  # `nvim_buf_create_user_command` when its client attaches (lua/rustaceanvim/commands/init.lua).
  # Hence these are registered per Rust buffer rather than globally - a global map would E492
  # everywhere else. `FileType` (instead of `LspAttach`) also means the keys exist while the
  # server is still indexing, and the maps point at `:RustLsp` by name, so the command only has
  # to exist at *invocation* time.
  #
  # Subcommand names are rustaceanvim 9.2.0's camelCase ones - `:RustLsp <Tab>` completes them.
  # Two from the plan do not exist in 9.x and are dropped: `runnables external` and cocogrep.
  # Neovim's own `gra`/`grn`/`grr`/`gri`/`grt` already cover code actions/rename/references.
  autoCmd = [
    {
      event = [ "FileType" ];
      pattern = [ "rust" ];
      desc = "Rust-specific keymaps (rustaceanvim)";
      callback.__raw = ''
        function()
          local map = function(lhs, rhs, desc)
            vim.keymap.set('n', lhs, rhs, { buffer = true, desc = desc })
          end
          map('<leader>rt', '<Cmd>RustLsp testables<CR>', 'Run testables')
          map('<leader>rr', '<Cmd>RustLsp runnables<CR>', 'Run runnables')
          map('<leader>rd', '<Cmd>RustLsp debuggables<CR>', 'Debug debuggables (nvim-dap + lldb-dap)')
          map('<leader>rp', '<Cmd>RustLsp parentModule<CR>', 'Open parent module')
          map('<leader>re', '<Cmd>RustLsp expandMacro<CR>', 'Expand macro (recursive)')
          map('<leader>rc', '<Cmd>RustLsp codeAction<CR>', 'Grouped code actions')
          map('<leader>rf', '<Cmd>RustLsp flyCheck run<CR>', 'cargo check (fly-check)')
          map('<leader>ro', '<Cmd>RustLsp openCargo<CR>', 'Open Cargo.toml of this package')
          map('<leader>rx', '<Cmd>RustLsp relatedDiagnostics<CR>', 'Related diagnostics -> quickfix')
        end
      '';
    }
  ];
}
